package org.pojos;
// Generated Feb 6, 2017 5:18:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * ActionTypes generated by hbm2java
 */
@Entity
@Table(name="action_types"
    ,schema="public"
)
public class ActionTypes  implements java.io.Serializable {


     private int id;
     private Clients clients;
     private Orgs orgs;
     private String actionTypeTitle;
     private short actionTypeStatus;
     private Set actionses = new HashSet(0);

    public ActionTypes() {
    }

	
    public ActionTypes(int id, String actionTypeTitle, short actionTypeStatus) {
        this.id = id;
        this.actionTypeTitle = actionTypeTitle;
        this.actionTypeStatus = actionTypeStatus;
    }
    public ActionTypes(int id, Clients clients, Orgs orgs, String actionTypeTitle, short actionTypeStatus, Set actionses) {
       this.id = id;
       this.clients = clients;
       this.orgs = orgs;
       this.actionTypeTitle = actionTypeTitle;
       this.actionTypeStatus = actionTypeStatus;
       this.actionses = actionses;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="client_id")
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="org_id")
    public Orgs getOrgs() {
        return this.orgs;
    }
    
    public void setOrgs(Orgs orgs) {
        this.orgs = orgs;
    }

    
    @Column(name="action_type_title", nullable=false)
    public String getActionTypeTitle() {
        return this.actionTypeTitle;
    }
    
    public void setActionTypeTitle(String actionTypeTitle) {
        this.actionTypeTitle = actionTypeTitle;
    }

    
    @Column(name="action_type_status", nullable=false)
    public short getActionTypeStatus() {
        return this.actionTypeStatus;
    }
    
    public void setActionTypeStatus(short actionTypeStatus) {
        this.actionTypeStatus = actionTypeStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="actionTypes")
    public Set getActionses() {
        return this.actionses;
    }
    
    public void setActionses(Set actionses) {
        this.actionses = actionses;
    }




}


