package org.pojos;
// Generated Jan 30, 2017 1:15:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ActionTypes generated by hbm2java
 */
@Entity
@Table(name="action_types"
    ,schema="public"
)
public class ActionTypes  implements java.io.Serializable {


     private int id;
     private String actionTypeTitle;
     private short actionTypeStatus;
     private Set actionses = new HashSet(0);

    public ActionTypes() {
    }

	
    public ActionTypes(int id, String actionTypeTitle, short actionTypeStatus) {
        this.id = id;
        this.actionTypeTitle = actionTypeTitle;
        this.actionTypeStatus = actionTypeStatus;
    }
    public ActionTypes(int id, String actionTypeTitle, short actionTypeStatus, Set actionses) {
       this.id = id;
       this.actionTypeTitle = actionTypeTitle;
       this.actionTypeStatus = actionTypeStatus;
       this.actionses = actionses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="action_type_title", nullable=false)
    public String getActionTypeTitle() {
        return this.actionTypeTitle;
    }
    
    public void setActionTypeTitle(String actionTypeTitle) {
        this.actionTypeTitle = actionTypeTitle;
    }

    
    @Column(name="action_type_status", nullable=false)
    public short getActionTypeStatus() {
        return this.actionTypeStatus;
    }
    
    public void setActionTypeStatus(short actionTypeStatus) {
        this.actionTypeStatus = actionTypeStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="actionTypes")
    public Set getActionses() {
        return this.actionses;
    }
    
    public void setActionses(Set actionses) {
        this.actionses = actionses;
    }




}


