package org.pojos;
// Generated Feb 6, 2017 5:18:07 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Calender generated by hbm2java
 */
@Entity
@Table(name = "calender", schema = "public"
)
public class Calender implements java.io.Serializable {

    private int id;
    private Clients clients;
    private Orgs orgs;
    private String calenderTitle;
    private int startDay = 1;
    private int transDay = 1;
    private Date startFrom;
    private Character type;
    private int weekTransDate;
    private int weekStartDay;
    private Set periodses = new HashSet(0);

    public Calender() {
    }

    public Calender(int id, String calenderTitle, int startDay, int transDay) {
        this.id = id;
        this.calenderTitle = calenderTitle;
        this.startDay = startDay;
        this.transDay = transDay;
    }

    public Calender(int id, Clients clients, Orgs orgs, String calenderTitle, int startDay, int transDay, Date startFrom, Character type, int weekTransDate, int weekStartDay, Set periodses) {
        this.id = id;
        this.clients = clients;
        this.orgs = orgs;
        this.calenderTitle = calenderTitle;
        this.startDay = startDay;
        this.transDay = transDay;
        this.startFrom = startFrom;
        this.type = type;
        this.weekTransDate = weekTransDate;
        this.weekStartDay = weekStartDay;
        this.periodses = periodses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "client_id")
    public Clients getClients() {
        return this.clients;
    }

    public void setClients(Clients clients) {
        this.clients = clients;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "org_id")
    public Orgs getOrgs() {
        return this.orgs;
    }

    public void setOrgs(Orgs orgs) {
        this.orgs = orgs;
    }

    @Column(name = "calender_title", nullable = false)
    public String getCalenderTitle() {
        return this.calenderTitle;
    }

    public void setCalenderTitle(String calenderTitle) {
        this.calenderTitle = calenderTitle;
    }

    @Column(name = "start_day", nullable = false, precision = 131089, scale = 0)
    public int getStartDay() {
        return this.startDay;
    }

    public void setStartDay(int startDay) {
        this.startDay = startDay;
    }

    @Column(name = "trans_day", nullable = false, precision = 131089, scale = 0)
    public int getTransDay() {
        return this.transDay;
    }

    public void setTransDay(int transDay) {
        this.transDay = transDay;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "start_from", length = 29)
    public Date getStartFrom() {
        return this.startFrom;
    }

    public void setStartFrom(Date startFrom) {
        this.startFrom = startFrom;
    }

    @Column(name = "type", length = 1)
    public Character getType() {
        return this.type;
    }

    public void setType(Character type) {
        this.type = type;
    }

    @Column(name = "week_trans_date", precision = 131089, scale = 0)
    public int getWeekTransDate() {
        return this.weekTransDate;
    }

    public void setWeekTransDate(int weekTransDate) {
        this.weekTransDate = weekTransDate;
    }

    @Column(name = "week_start_day", precision = 131089, scale = 0)
    public int getWeekStartDay() {
        return this.weekStartDay;
    }

    public void setWeekStartDay(int weekStartDay) {
        this.weekStartDay = weekStartDay;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "calender")
    public Set getPeriodses() {
        return this.periodses;
    }

    public void setPeriodses(Set periodses) {
        this.periodses = periodses;
    }

}
