package org.pojos;
// Generated Jan 30, 2017 1:15:59 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cities generated by hbm2java
 */
@Entity
@Table(name = "cities", schema = "public"
)
public class Cities implements java.io.Serializable {

    private int id;
    private String cityTitle;
    private boolean cityStatus = true;
    private Set employeeses = new HashSet(0);
    private boolean canEdit = false;

    public Cities() {
    }

    public Cities(int id, String cityTitle, boolean cityStatus) {
        this.id = id;
        this.cityTitle = cityTitle;
        this.cityStatus = cityStatus;
    }

    public Cities(int id, String cityTitle, boolean cityStatus, Set employeeses) {
        this.id = id;
        this.cityTitle = cityTitle;
        this.cityStatus = cityStatus;
        this.employeeses = employeeses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "city_title", nullable = false)
    public String getCityTitle() {
        return this.cityTitle;
    }

    public void setCityTitle(String cityTitle) {
        this.cityTitle = cityTitle;
    }

    @Column(name = "city_status", nullable = false)
    public boolean getCityStatus() {
        return this.cityStatus;
    }

    public void setCityStatus(boolean cityStatus) {
        this.cityStatus = cityStatus;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cities")
    public Set getEmployeeses() {
        return this.employeeses;
    }

    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }

    public boolean isCanEdit() {
        return canEdit;
    }

    public void setCanEdit(boolean canEdit) {
        this.canEdit = canEdit;
    }

}
