package org.pojos;
// Generated Feb 6, 2017 5:18:07 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Degrees generated by hbm2java
 */
@Entity
@Table(name = "degrees", schema = "public"
)
public class Degrees implements java.io.Serializable {

    private int id;
    private Clients clients;
    private Orgs orgs;
    private String degreeTitle;
    private boolean degreeStatus = true;
    private Set employeeses = new HashSet(0);

    public Degrees() {
    }

    public Degrees(int id, String degreeTitle, boolean degreeStatus) {
        this.id = id;
        this.degreeTitle = degreeTitle;
        this.degreeStatus = degreeStatus;
    }

    public Degrees(int id, Clients clients, Orgs orgs, String degreeTitle, boolean degreeStatus, Set employeeses) {
        this.id = id;
        this.clients = clients;
        this.orgs = orgs;
        this.degreeTitle = degreeTitle;
        this.degreeStatus = degreeStatus;
        this.employeeses = employeeses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "client_id")
    public Clients getClients() {
        return this.clients;
    }

    public void setClients(Clients clients) {
        this.clients = clients;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "org_id")
    public Orgs getOrgs() {
        return this.orgs;
    }

    public void setOrgs(Orgs orgs) {
        this.orgs = orgs;
    }

    @Column(name = "degree_title", nullable = false)
    public String getDegreeTitle() {
        return this.degreeTitle;
    }

    public void setDegreeTitle(String degreeTitle) {
        this.degreeTitle = degreeTitle;
    }

    @Column(name = "degree_status", nullable = false)
    public boolean isDegreeStatus() {
        return this.degreeStatus;
    }

    public void setDegreeStatus(boolean degreeStatus) {
        this.degreeStatus = degreeStatus;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "degrees")
    public Set getEmployeeses() {
        return this.employeeses;
    }

    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }

}
