package org.pojos;
// Generated Feb 6, 2017 5:18:07 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departments generated by hbm2java
 */
@Entity
@Table(name = "departments", schema = "public"
)
public class Departments implements java.io.Serializable {

    private int id;
    private Clients clients;
    private Orgs orgs;
    private String deptTitle;
    private boolean deptStatus = true;
    private Set payrollTemplateses = new HashSet(0);
    private Set payrollProcesseses = new HashSet(0);
    private Set employeeses = new HashSet(0);

    private boolean canEdit = false;

    public Departments() {
    }

    public Departments(int id, String deptTitle, boolean deptStatus) {
        this.id = id;
        this.deptTitle = deptTitle;
        this.deptStatus = deptStatus;
    }

    public Departments(int id, Clients clients, Orgs orgs, String deptTitle, boolean deptStatus, Set payrollTemplateses, Set payrollProcesseses, Set employeeses) {
        this.id = id;
        this.clients = clients;
        this.orgs = orgs;
        this.deptTitle = deptTitle;
        this.deptStatus = deptStatus;
        this.payrollTemplateses = payrollTemplateses;
        this.payrollProcesseses = payrollProcesseses;
        this.employeeses = employeeses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "client_id")
    public Clients getClients() {
        return this.clients;
    }

    public void setClients(Clients clients) {
        this.clients = clients;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "org_id")
    public Orgs getOrgs() {
        return this.orgs;
    }

    public void setOrgs(Orgs orgs) {
        this.orgs = orgs;
    }

    @Column(name = "dept_title", nullable = false)
    public String getDeptTitle() {
        return this.deptTitle;
    }

    public void setDeptTitle(String deptTitle) {
        this.deptTitle = deptTitle;
    }

    @Column(name = "dept_status", nullable = false)
    public boolean isDeptStatus() {
        return this.deptStatus;
    }

    public void setDeptStatus(boolean deptStatus) {
        this.deptStatus = deptStatus;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "departments")
    public Set getPayrollTemplateses() {
        return this.payrollTemplateses;
    }

    public void setPayrollTemplateses(Set payrollTemplateses) {
        this.payrollTemplateses = payrollTemplateses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "departments")
    public Set getPayrollProcesseses() {
        return this.payrollProcesseses;
    }

    public void setPayrollProcesseses(Set payrollProcesseses) {
        this.payrollProcesseses = payrollProcesseses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "departments")
    public Set getEmployeeses() {
        return this.employeeses;
    }

    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }

    public boolean isCanEdit() {
        return canEdit;
    }

    public void setCanEdit(boolean canEdit) {
        this.canEdit = canEdit;
    }

}
