package org.pojos;
// Generated Jan 30, 2017 1:15:59 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name = "employees", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "emp_id")
)
public class Employees implements java.io.Serializable {

    private int id;
    private Cities cities;
    private Degrees degrees;
    private Departments departments;
    private MaritalStatus maritalStatus;
    private MilitaryStatus militaryStatus;
    private Positions positions;
    private String empFullname;
    private Date empHiringdate;
    private Date empBirthdate;
    private short empStatus;
    private String empId;
    private boolean isuser;
    private Set actionsTranses = new HashSet(0);
    private Set processesAmountses = new HashSet(0);
    private Set payrollEmployeeItemses = new HashSet(0);

    public Employees() {
    }

    public Employees(int id, short empStatus, boolean isuser) {
        this.id = id;
        this.empStatus = empStatus;
        this.isuser = isuser;
    }

    public Employees(int id, Cities cities, Degrees degrees, Departments departments, MaritalStatus maritalStatus, MilitaryStatus militaryStatus, Positions positions, String empFullname, Date empHiringdate, Date empBirthdate, short empStatus, String empId, boolean isuser, Set actionsTranses, Set processesAmountses, Set payrollEmployeeItemses) {
        this.id = id;
        this.cities = cities;
        this.degrees = degrees;
        this.departments = departments;
        this.maritalStatus = maritalStatus;
        this.militaryStatus = militaryStatus;
        this.positions = positions;
        this.empFullname = empFullname;
        this.empHiringdate = empHiringdate;
        this.empBirthdate = empBirthdate;
        this.empStatus = empStatus;
        this.empId = empId;
        this.isuser = isuser;
        this.actionsTranses = actionsTranses;
        this.processesAmountses = processesAmountses;
        this.payrollEmployeeItemses = payrollEmployeeItemses;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "emp_city")
    public Cities getCities() {
        return this.cities;
    }

    public void setCities(Cities cities) {
        this.cities = cities;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "emp_degree")
    public Degrees getDegrees() {
        return this.degrees;
    }

    public void setDegrees(Degrees degrees) {
        this.degrees = degrees;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "emp_department")
    public Departments getDepartments() {
        return this.departments;
    }

    public void setDepartments(Departments departments) {
        this.departments = departments;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "emp_maritalstatus")
    public MaritalStatus getMaritalStatus() {
        return this.maritalStatus;
    }

    public void setMaritalStatus(MaritalStatus maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "emp_militarystatus")
    public MilitaryStatus getMilitaryStatus() {
        return this.militaryStatus;
    }

    public void setMilitaryStatus(MilitaryStatus militaryStatus) {
        this.militaryStatus = militaryStatus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "emp_position")
    public Positions getPositions() {
        return this.positions;
    }

    public void setPositions(Positions positions) {
        this.positions = positions;
    }

    @Column(name = "emp_fullname")
    public String getEmpFullname() {
        return this.empFullname;
    }

    public void setEmpFullname(String empFullname) {
        this.empFullname = empFullname;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "emp_hiringdate", length = 29)
    public Date getEmpHiringdate() {
        return this.empHiringdate;
    }

    public void setEmpHiringdate(Date empHiringdate) {
        this.empHiringdate = empHiringdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "emp_birthdate", length = 29)
    public Date getEmpBirthdate() {
        return this.empBirthdate;
    }

    public void setEmpBirthdate(Date empBirthdate) {
        this.empBirthdate = empBirthdate;
    }

    @Column(name = "emp_status", nullable = false)
    public short getEmpStatus() {
        return this.empStatus;
    }

    public void setEmpStatus(short empStatus) {
        this.empStatus = empStatus;
    }

    @Column(name = "emp_id", unique = true)
    public String getEmpId() {
        return this.empId;
    }

    public void setEmpId(String empId) {
        this.empId = empId;
    }

    @Column(name = "isuser", nullable = false)
    public boolean isIsuser() {
        return this.isuser;
    }

    public void setIsuser(boolean isuser) {
        this.isuser = isuser;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
    public Set getActionsTranses() {
        return this.actionsTranses;
    }

    public void setActionsTranses(Set actionsTranses) {
        this.actionsTranses = actionsTranses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
    public Set getProcessesAmountses() {
        return this.processesAmountses;
    }

    public void setProcessesAmountses(Set processesAmountses) {
        this.processesAmountses = processesAmountses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
    public Set getPayrollEmployeeItemses() {
        return this.payrollEmployeeItemses;
    }

    public void setPayrollEmployeeItemses(Set payrollEmployeeItemses) {
        this.payrollEmployeeItemses = payrollEmployeeItemses;
    }

}
