package org.pojos;
// Generated Jan 30, 2017 1:15:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MaritalStatus generated by hbm2java
 */
@Entity
@Table(name="marital_status"
    ,schema="public"
)
public class MaritalStatus  implements java.io.Serializable {


     private int id;
     private String maritalTitle;
     private short maritalStatus;
     private Set employeeses = new HashSet(0);

    public MaritalStatus() {
    }

	
    public MaritalStatus(int id, String maritalTitle, short maritalStatus) {
        this.id = id;
        this.maritalTitle = maritalTitle;
        this.maritalStatus = maritalStatus;
    }
    public MaritalStatus(int id, String maritalTitle, short maritalStatus, Set employeeses) {
       this.id = id;
       this.maritalTitle = maritalTitle;
       this.maritalStatus = maritalStatus;
       this.employeeses = employeeses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="marital_title", nullable=false)
    public String getMaritalTitle() {
        return this.maritalTitle;
    }
    
    public void setMaritalTitle(String maritalTitle) {
        this.maritalTitle = maritalTitle;
    }

    
    @Column(name="marital_status", nullable=false)
    public short getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(short maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="maritalStatus")
    public Set getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }




}


