package org.pojos;
// Generated Feb 6, 2017 5:18:07 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MilitaryStatus generated by hbm2java
 */
@Entity
@Table(name = "military_status", schema = "public"
)
public class MilitaryStatus implements java.io.Serializable {

    private int id;
    private Clients clients;
    private Orgs orgs;
    private String militaryTitle;
    private boolean militaryStatus = true;
    private Set employeeses = new HashSet(0);

    public MilitaryStatus() {
    }

    public MilitaryStatus(int id, String militaryTitle, boolean militaryStatus) {
        this.id = id;
        this.militaryTitle = militaryTitle;
        this.militaryStatus = militaryStatus;
    }

    public MilitaryStatus(int id, Clients clients, Orgs orgs, String militaryTitle, boolean militaryStatus, Set employeeses) {
        this.id = id;
        this.clients = clients;
        this.orgs = orgs;
        this.militaryTitle = militaryTitle;
        this.militaryStatus = militaryStatus;
        this.employeeses = employeeses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "client_id")
    public Clients getClients() {
        return this.clients;
    }

    public void setClients(Clients clients) {
        this.clients = clients;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "org_id")
    public Orgs getOrgs() {
        return this.orgs;
    }

    public void setOrgs(Orgs orgs) {
        this.orgs = orgs;
    }

    @Column(name = "military_title", nullable = false)
    public String getMilitaryTitle() {
        return this.militaryTitle;
    }

    public void setMilitaryTitle(String militaryTitle) {
        this.militaryTitle = militaryTitle;
    }

    @Column(name = "military_status", nullable = false)
    public boolean isMilitaryStatus() {
        return this.militaryStatus;
    }

    public void setMilitaryStatus(boolean militaryStatus) {
        this.militaryStatus = militaryStatus;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "militaryStatus")
    public Set getEmployeeses() {
        return this.employeeses;
    }

    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }
}
