package org.pojos;
// Generated Feb 6, 2017 5:18:07 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Orgs generated by hbm2java
 */
@Entity
@Table(name = "orgs", schema = "public"
)
public class Orgs implements java.io.Serializable {

    private int id;
    private Clients clients;
    private String orgName;
    private boolean orgStatus = true;
    private String orgDesc;
    private Set periodses = new HashSet(0);
    private Set calenders = new HashSet(0);
    private Set degreeses = new HashSet(0);
    private Set positionses = new HashSet(0);
    private Set payrollEmployeeItemses = new HashSet(0);
    private Set employeeses = new HashSet(0);
    private Set departmentses = new HashSet(0);
    private Set payrollItemsCatses = new HashSet(0);
    private Set actionsTranses = new HashSet(0);
    private Set citieses = new HashSet(0);
    private Set payrollProcesseses = new HashSet(0);
    private Set maritalStatuses = new HashSet(0);
    private Set payrollItemses = new HashSet(0);
    private Set actionTypeses = new HashSet(0);
    private Set militaryStatuses = new HashSet(0);
    private Set payrollTemplateses = new HashSet(0);
    private Set payrollFormulases = new HashSet(0);

    private int client_id;
    private boolean canEdit = false;

    public Orgs() {
    }

    public Orgs(int id, boolean orgStatus) {
        this.id = id;
        this.orgStatus = orgStatus;
    }

    public Orgs(int id, Clients clients, String orgName, boolean orgStatus, String orgDesc, Set periodses, Set calenders, Set degreeses, Set positionses, Set payrollEmployeeItemses, Set employeeses, Set departmentses, Set payrollItemsCatses, Set actionsTranses, Set citieses, Set payrollProcesseses, Set maritalStatuses, Set payrollItemses, Set actionTypeses, Set militaryStatuses, Set payrollTemplateses, Set payrollFormulases) {
        this.id = id;
        this.clients = clients;
        this.orgName = orgName;
        this.orgStatus = orgStatus;
        this.orgDesc = orgDesc;
        this.periodses = periodses;
        this.calenders = calenders;
        this.degreeses = degreeses;
        this.positionses = positionses;
        this.payrollEmployeeItemses = payrollEmployeeItemses;
        this.employeeses = employeeses;
        this.departmentses = departmentses;
        this.payrollItemsCatses = payrollItemsCatses;
        this.actionsTranses = actionsTranses;
        this.citieses = citieses;
        this.payrollProcesseses = payrollProcesseses;
        this.maritalStatuses = maritalStatuses;
        this.payrollItemses = payrollItemses;
        this.actionTypeses = actionTypeses;
        this.militaryStatuses = militaryStatuses;
        this.payrollTemplateses = payrollTemplateses;
        this.payrollFormulases = payrollFormulases;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "client_id")
    public Clients getClients() {
        return this.clients;
    }

    public void setClients(Clients clients) {
        this.clients = clients;
    }

    @Column(name = "org_name")
    public String getOrgName() {
        return this.orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    @Column(name = "org_status", nullable = false)
    public boolean isOrgStatus() {
        return this.orgStatus;
    }

    public void setOrgStatus(boolean orgStatus) {
        this.orgStatus = orgStatus;
    }

    @Column(name = "org_desc")
    public String getOrgDesc() {
        return this.orgDesc;
    }

    public void setOrgDesc(String orgDesc) {
        this.orgDesc = orgDesc;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orgs")
    public Set getPeriodses() {
        return this.periodses;
    }

    public void setPeriodses(Set periodses) {
        this.periodses = periodses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orgs")
    public Set getCalenders() {
        return this.calenders;
    }

    public void setCalenders(Set calenders) {
        this.calenders = calenders;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orgs")
    public Set getDegreeses() {
        return this.degreeses;
    }

    public void setDegreeses(Set degreeses) {
        this.degreeses = degreeses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orgs")
    public Set getPositionses() {
        return this.positionses;
    }

    public void setPositionses(Set positionses) {
        this.positionses = positionses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orgs")
    public Set getPayrollEmployeeItemses() {
        return this.payrollEmployeeItemses;
    }

    public void setPayrollEmployeeItemses(Set payrollEmployeeItemses) {
        this.payrollEmployeeItemses = payrollEmployeeItemses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orgs")
    public Set getEmployeeses() {
        return this.employeeses;
    }

    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orgs")
    public Set getDepartmentses() {
        return this.departmentses;
    }

    public void setDepartmentses(Set departmentses) {
        this.departmentses = departmentses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orgs")
    public Set getPayrollItemsCatses() {
        return this.payrollItemsCatses;
    }

    public void setPayrollItemsCatses(Set payrollItemsCatses) {
        this.payrollItemsCatses = payrollItemsCatses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orgs")
    public Set getActionsTranses() {
        return this.actionsTranses;
    }

    public void setActionsTranses(Set actionsTranses) {
        this.actionsTranses = actionsTranses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orgs")
    public Set getCitieses() {
        return this.citieses;
    }

    public void setCitieses(Set citieses) {
        this.citieses = citieses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orgs")
    public Set getPayrollProcesseses() {
        return this.payrollProcesseses;
    }

    public void setPayrollProcesseses(Set payrollProcesseses) {
        this.payrollProcesseses = payrollProcesseses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orgs")
    public Set getMaritalStatuses() {
        return this.maritalStatuses;
    }

    public void setMaritalStatuses(Set maritalStatuses) {
        this.maritalStatuses = maritalStatuses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orgs")
    public Set getPayrollItemses() {
        return this.payrollItemses;
    }

    public void setPayrollItemses(Set payrollItemses) {
        this.payrollItemses = payrollItemses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orgs")
    public Set getActionTypeses() {
        return this.actionTypeses;
    }

    public void setActionTypeses(Set actionTypeses) {
        this.actionTypeses = actionTypeses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orgs")
    public Set getMilitaryStatuses() {
        return this.militaryStatuses;
    }

    public void setMilitaryStatuses(Set militaryStatuses) {
        this.militaryStatuses = militaryStatuses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orgs")
    public Set getPayrollTemplateses() {
        return this.payrollTemplateses;
    }

    public void setPayrollTemplateses(Set payrollTemplateses) {
        this.payrollTemplateses = payrollTemplateses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "orgs")
    public Set getPayrollFormulases() {
        return this.payrollFormulases;
    }

    public void setPayrollFormulases(Set payrollFormulases) {
        this.payrollFormulases = payrollFormulases;
    }

    public int getClient_id() {
        return client_id;
    }

    public void setClient_id(int client_id) {
        this.client_id = client_id;
    }

    public boolean isCanEdit() {
        return canEdit;
    }

    public void setCanEdit(boolean canEdit) {
        this.canEdit = canEdit;
    }

    @Override
    public String toString() {
        return "Orgs{" + "id=" + id + ", orgName=" + orgName + '}';
    }

}
