package org.pojos;
// Generated Jan 30, 2017 1:15:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PayrollItemsCats generated by hbm2java
 */
@Entity
@Table(name="payroll_items_cats"
    ,schema="public"
)
public class PayrollItemsCats  implements java.io.Serializable {


     private int id;
     private String payrollCatTitle;
     private short payrollCatStatus;
     private Set payrollItemses = new HashSet(0);

    public PayrollItemsCats() {
    }

	
    public PayrollItemsCats(int id, String payrollCatTitle, short payrollCatStatus) {
        this.id = id;
        this.payrollCatTitle = payrollCatTitle;
        this.payrollCatStatus = payrollCatStatus;
    }
    public PayrollItemsCats(int id, String payrollCatTitle, short payrollCatStatus, Set payrollItemses) {
       this.id = id;
       this.payrollCatTitle = payrollCatTitle;
       this.payrollCatStatus = payrollCatStatus;
       this.payrollItemses = payrollItemses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="payroll_cat_title", nullable=false)
    public String getPayrollCatTitle() {
        return this.payrollCatTitle;
    }
    
    public void setPayrollCatTitle(String payrollCatTitle) {
        this.payrollCatTitle = payrollCatTitle;
    }

    
    @Column(name="payroll_cat_status", nullable=false)
    public short getPayrollCatStatus() {
        return this.payrollCatStatus;
    }
    
    public void setPayrollCatStatus(short payrollCatStatus) {
        this.payrollCatStatus = payrollCatStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="payrollItemsCats")
    public Set getPayrollItemses() {
        return this.payrollItemses;
    }
    
    public void setPayrollItemses(Set payrollItemses) {
        this.payrollItemses = payrollItemses;
    }




}


