package org.pojos;
// Generated Feb 6, 2017 5:18:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PayrollProcesses generated by hbm2java
 */
@Entity
@Table(name="payroll_processes"
    ,schema="public"
)
public class PayrollProcesses  implements java.io.Serializable {


     private int id;
     private Clients clients;
     private Departments departments;
     private Orgs orgs;
     private Periods periods;
     private String title;
     private Short locked;
     private Set processesAmountses = new HashSet(0);

    public PayrollProcesses() {
    }

	
    public PayrollProcesses(int id) {
        this.id = id;
    }
    public PayrollProcesses(int id, Clients clients, Departments departments, Orgs orgs, Periods periods, String title, Short locked, Set processesAmountses) {
       this.id = id;
       this.clients = clients;
       this.departments = departments;
       this.orgs = orgs;
       this.periods = periods;
       this.title = title;
       this.locked = locked;
       this.processesAmountses = processesAmountses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="client_id")
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dept_id")
    public Departments getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Departments departments) {
        this.departments = departments;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="org_id")
    public Orgs getOrgs() {
        return this.orgs;
    }
    
    public void setOrgs(Orgs orgs) {
        this.orgs = orgs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="period_id")
    public Periods getPeriods() {
        return this.periods;
    }
    
    public void setPeriods(Periods periods) {
        this.periods = periods;
    }

    
    @Column(name="title")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="locked")
    public Short getLocked() {
        return this.locked;
    }
    
    public void setLocked(Short locked) {
        this.locked = locked;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="payrollProcesses")
    public Set getProcessesAmountses() {
        return this.processesAmountses;
    }
    
    public void setProcessesAmountses(Set processesAmountses) {
        this.processesAmountses = processesAmountses;
    }




}


