package org.pojos;
// Generated Feb 6, 2017 5:18:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PayrollItems generated by hbm2java
 */
@Entity
@Table(name="payroll_items"
    ,schema="public"
)
public class PayrollItems  implements java.io.Serializable {


     private int id;
     private Clients clients;
     private Orgs orgs;
     private PayrollItemsCats payrollItemsCats;
     private String title;
     private String type;
     private Short status;
     private Character process;
     private Date activeFrom;
     private Set processesAmountses = new HashSet(0);
     private Set payrollTemplatesItemses = new HashSet(0);
     private Set payrollFormulases = new HashSet(0);
     private Set payrollEmployeeItemses = new HashSet(0);

    public PayrollItems() {
    }

	
    public PayrollItems(int id) {
        this.id = id;
    }
    public PayrollItems(int id, Clients clients, Orgs orgs, PayrollItemsCats payrollItemsCats, String title, String type, Short status, Character process, Date activeFrom, Set processesAmountses, Set payrollTemplatesItemses, Set payrollFormulases, Set payrollEmployeeItemses) {
       this.id = id;
       this.clients = clients;
       this.orgs = orgs;
       this.payrollItemsCats = payrollItemsCats;
       this.title = title;
       this.type = type;
       this.status = status;
       this.process = process;
       this.activeFrom = activeFrom;
       this.processesAmountses = processesAmountses;
       this.payrollTemplatesItemses = payrollTemplatesItemses;
       this.payrollFormulases = payrollFormulases;
       this.payrollEmployeeItemses = payrollEmployeeItemses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="client_id")
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="org_id")
    public Orgs getOrgs() {
        return this.orgs;
    }
    
    public void setOrgs(Orgs orgs) {
        this.orgs = orgs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="catid")
    public PayrollItemsCats getPayrollItemsCats() {
        return this.payrollItemsCats;
    }
    
    public void setPayrollItemsCats(PayrollItemsCats payrollItemsCats) {
        this.payrollItemsCats = payrollItemsCats;
    }

    
    @Column(name="title")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="type", length=3)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="status")
    public Short getStatus() {
        return this.status;
    }
    
    public void setStatus(Short status) {
        this.status = status;
    }

    
    @Column(name="process", length=1)
    public Character getProcess() {
        return this.process;
    }
    
    public void setProcess(Character process) {
        this.process = process;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="active_from", length=29)
    public Date getActiveFrom() {
        return this.activeFrom;
    }
    
    public void setActiveFrom(Date activeFrom) {
        this.activeFrom = activeFrom;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="payrollItems")
    public Set getProcessesAmountses() {
        return this.processesAmountses;
    }
    
    public void setProcessesAmountses(Set processesAmountses) {
        this.processesAmountses = processesAmountses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="payrollItems")
    public Set getPayrollTemplatesItemses() {
        return this.payrollTemplatesItemses;
    }
    
    public void setPayrollTemplatesItemses(Set payrollTemplatesItemses) {
        this.payrollTemplatesItemses = payrollTemplatesItemses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="payrollItems")
    public Set getPayrollFormulases() {
        return this.payrollFormulases;
    }
    
    public void setPayrollFormulases(Set payrollFormulases) {
        this.payrollFormulases = payrollFormulases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="payrollItems")
    public Set getPayrollEmployeeItemses() {
        return this.payrollEmployeeItemses;
    }
    
    public void setPayrollEmployeeItemses(Set payrollEmployeeItemses) {
        this.payrollEmployeeItemses = payrollEmployeeItemses;
    }




}


