package org.pojos;
// Generated Feb 6, 2017 5:18:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PayrollTemplates generated by hbm2java
 */
@Entity
@Table(name="payroll_templates"
    ,schema="public"
)
public class PayrollTemplates  implements java.io.Serializable {


     private int id;
     private Clients clients;
     private Departments departments;
     private Orgs orgs;
     private String title;
     private Short status;
     private Set payrollTemplatesItemses = new HashSet(0);

    public PayrollTemplates() {
    }

	
    public PayrollTemplates(int id) {
        this.id = id;
    }
    public PayrollTemplates(int id, Clients clients, Departments departments, Orgs orgs, String title, Short status, Set payrollTemplatesItemses) {
       this.id = id;
       this.clients = clients;
       this.departments = departments;
       this.orgs = orgs;
       this.title = title;
       this.status = status;
       this.payrollTemplatesItemses = payrollTemplatesItemses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="client_id")
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dept_id")
    public Departments getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Departments departments) {
        this.departments = departments;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="org_id")
    public Orgs getOrgs() {
        return this.orgs;
    }
    
    public void setOrgs(Orgs orgs) {
        this.orgs = orgs;
    }

    
    @Column(name="title")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="status")
    public Short getStatus() {
        return this.status;
    }
    
    public void setStatus(Short status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="payrollTemplates")
    public Set getPayrollTemplatesItemses() {
        return this.payrollTemplatesItemses;
    }
    
    public void setPayrollTemplatesItemses(Set payrollTemplatesItemses) {
        this.payrollTemplatesItemses = payrollTemplatesItemses;
    }




}


