package org.pojos;
// Generated Feb 6, 2017 5:18:07 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PayrollFormulas generated by hbm2java
 */
@Entity
@Table(name="payroll_formulas"
    ,schema="public"
)
public class PayrollFormulas  implements java.io.Serializable {


     private int id;
     private Clients clients;
     private Orgs orgs;
     private PayrollItems payrollItems;
     private String formula;

    public PayrollFormulas() {
    }

	
    public PayrollFormulas(int id) {
        this.id = id;
    }
    public PayrollFormulas(int id, Clients clients, Orgs orgs, PayrollItems payrollItems, String formula) {
       this.id = id;
       this.clients = clients;
       this.orgs = orgs;
       this.payrollItems = payrollItems;
       this.formula = formula;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="client_id")
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="org_id")
    public Orgs getOrgs() {
        return this.orgs;
    }
    
    public void setOrgs(Orgs orgs) {
        this.orgs = orgs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="item_id")
    public PayrollItems getPayrollItems() {
        return this.payrollItems;
    }
    
    public void setPayrollItems(PayrollItems payrollItems) {
        this.payrollItems = payrollItems;
    }

    
    @Column(name="formula")
    public String getFormula() {
        return this.formula;
    }
    
    public void setFormula(String formula) {
        this.formula = formula;
    }




}


