package org.pojos;
// Generated Jan 30, 2017 1:15:59 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Positions generated by hbm2java
 */
@Entity
@Table(name = "positions", schema = "public"
)
public class Positions implements java.io.Serializable {

    private int id;
    private String posTitle;
    private boolean posStatus = true;
    private Set employeeses = new HashSet(0);

    private Clients client;
    private Orgs org;

    private boolean canEdit = false;

    public Positions() {
    }

    public Positions(int id, String posTitle, boolean posStatus) {
        this.id = id;
        this.posTitle = posTitle;
        this.posStatus = posStatus;
    }

    public Positions(int id, String posTitle, boolean posStatus, Set employeeses) {
        this.id = id;
        this.posTitle = posTitle;
        this.posStatus = posStatus;
        this.employeeses = employeeses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "pos_title", nullable = false)
    public String getPosTitle() {
        return this.posTitle;
    }

    public void setPosTitle(String posTitle) {
        this.posTitle = posTitle;
    }

    @Column(name = "pos_status", nullable = false)
    public boolean getPosStatus() {
        return this.posStatus;
    }

    public void setPosStatus(boolean posStatus) {
        this.posStatus = posStatus;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "positions")
    public Set getEmployeeses() {
        return this.employeeses;
    }

    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "client_id")
    public Clients getClient() {
        return client;
    }

    public void setClient(Clients client) {
        this.client = client;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "org_id")
    public Orgs getOrg() {
        return org;
    }

    public void setOrg(Orgs org) {
        this.org = org;
    }

    public boolean isCanEdit() {
        return canEdit;
    }

    public void setCanEdit(boolean canEdit) {
        this.canEdit = canEdit;
    }

}
