package org.pojos;
// Generated Jan 30, 2017 1:15:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Positions generated by hbm2java
 */
@Entity
@Table(name="positions"
    ,schema="public"
)
public class Positions  implements java.io.Serializable {


     private int id;
     private String posTitle;
     private short posStatus;
     private Set employeeses = new HashSet(0);

    public Positions() {
    }

	
    public Positions(int id, String posTitle, short posStatus) {
        this.id = id;
        this.posTitle = posTitle;
        this.posStatus = posStatus;
    }
    public Positions(int id, String posTitle, short posStatus, Set employeeses) {
       this.id = id;
       this.posTitle = posTitle;
       this.posStatus = posStatus;
       this.employeeses = employeeses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="pos_title", nullable=false)
    public String getPosTitle() {
        return this.posTitle;
    }
    
    public void setPosTitle(String posTitle) {
        this.posTitle = posTitle;
    }

    
    @Column(name="pos_status", nullable=false)
    public short getPosStatus() {
        return this.posStatus;
    }
    
    public void setPosStatus(short posStatus) {
        this.posStatus = posStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="positions")
    public Set getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }




}


