package org.pojos;
// Generated Feb 6, 2017 5:18:07 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProcessesAmounts generated by hbm2java
 */
@Entity
@Table(name = "processes_amounts", schema = "public"
)
public class ProcessesAmounts implements java.io.Serializable {

    private int id;
    private Employees employees;
    private PayrollItems payrollItems;
    private PayrollProcesses payrollProcesses;
    private Periods periods;
    private BigDecimal amount;

    public ProcessesAmounts() {
    }

    public ProcessesAmounts(int id) {
        this.id = id;
    }

    public ProcessesAmounts(int id, Employees employees, PayrollItems payrollItems, PayrollProcesses payrollProcesses, Periods periods, BigDecimal amount) {
        this.id = id;
        this.employees = employees;
        this.payrollItems = payrollItems;
        this.payrollProcesses = payrollProcesses;
        this.periods = periods;
        this.amount = amount;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "emp_id")
    public Employees getEmployees() {
        return this.employees;
    }

    public void setEmployees(Employees employees) {
        this.employees = employees;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "item_id")
    public PayrollItems getPayrollItems() {
        return this.payrollItems;
    }

    public void setPayrollItems(PayrollItems payrollItems) {
        this.payrollItems = payrollItems;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "process_id")
    public PayrollProcesses getPayrollProcesses() {
        return this.payrollProcesses;
    }

    public void setPayrollProcesses(PayrollProcesses payrollProcesses) {
        this.payrollProcesses = payrollProcesses;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "period_id")
    public Periods getPeriods() {
        return this.periods;
    }

    public void setPeriods(Periods periods) {
        this.periods = periods;
    }

    @Column(name = "amount", precision = 131089, scale = 0)
    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

}
